pipeline {
    agent any

    environment {
        VENV = 'venv'
        DOCKER_IMAGE = 'your-dockerhub-username/messaging-app:latest'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/Douglaskhembo/alx-backend-python.git',
                    credentialsId: 'github-creds'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'python3 -m venv venv'
                sh './venv/bin/pip3 install --upgrade pip'
                sh './venv/bin/pip3 install -r messaging_app/Requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                sh './venv/bin/pytest messaging_app/chats/tests.py --junitxml=report.xml || true'
            }
        }

        stage('Publish Test Report') {
            steps {
                junit 'report.xml'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh 'docker build -t $DOCKER_IMAGE -f messaging_app/Dockerfile .'
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh """
                        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                        docker push $DOCKER_IMAGE
                    """
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
