pipeline {
    agent any

    environment {
        VENV = 'venv'
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/Douglaskhembo/alx-backend-python.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'python3 -m venv venv'
                sh './venv/bin/pip install --upgrade pip'
                sh './venv/bin/pip install -r Requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                // Target the correct path for tests
                sh './venv/bin/pytest messaging_app/chats/tests.py --junitxml=report.xml || true'
            }
        }

        stage('Publish Test Report') {
            steps {
                junit 'report.xml'
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
