#!/bin/bash

# Apply blue and green deployments
kubectl apply -f blue_deployment.yaml
kubectl apply -f green_deployment.yaml

# Apply or update the service
kubectl apply -f kubeservice.yaml

# Check logs of green deployment to verify
GREEN_POD=$(kubectl get pods -l app=messaging-app-green -o jsonpath="{.items[0].metadata.name}")
kubectl logs "$GREEN_POD"
